apiVersion: v1
kind: Service
metadata:
  name: frontend
  annotations:
    # Add this annotation if you're using ALB
    alb.ingress.kubernetes.io/healthcheck-path: /
spec:
  type: ClusterIP
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
